# experiment
name: "fusion-in-decoder_submission"
seed: 2022

# dataset
train_data: "/app/datasets/fusion_in_decoder/DprRetrieved/train.jsonl"
eval_data: "/app/datasets/fusion_in_decoder/Submission/test.jsonl"
checkpoint_dir: "/app/generators/fusion_in_decoder/models_and_results/baseline"

# model
model_name_or_path: "sonoisa/t5-base-japanese"
model_path: "/app/generators/fusion_in_decoder/models_and_results/baseline"
n_context: 60
text_maxlength: 250

# others
per_gpu_batch_size: 1
write_results: true
eval_print_freq: 2000

is_distributed: False
