# experiment
name: "fusion-in-decoder_test"
seed: 2022

# dataset
train_data: "/code/AIO3_FiD_baseline/datasets/fusion_in_decoder/DprRetrieved/train.jsonl"
eval_data: "/code/AIO3_FiD_baseline/datasets/fusion_in_decoder/DprRetrieved/test.jsonl"
checkpoint_dir: "models_and_results/baseline"

# model 
model_name_or_path: "sonoisa/t5-base-japanese"
model_path: "models_and_results/baseline"
n_context: 60
text_maxlength: 250

# others
per_gpu_batch_size: 1
write_results: true
eval_print_freq: 2000

is_distributed: False
